-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 22:53:32 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema vieiracf1_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vieiracf1_db` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`2014Fall_ExerciseType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`2014Fall_ExerciseType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vieiracf1_db`.`2014Fall_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vieiracf1_db`.`2014Fall_User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `weight` FLOAT NOT NULL,
  `goal_weight` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`2014Fall_User_Weight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`2014Fall_User_Weight` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `wieght` FLOAT NOT NULL,
  `2014Fall_User_id` INT(11) NOT NULL,
  INDEX `fk_2014Fall_User_Weight_2014Fall_User_idx` (`2014Fall_User_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_2014Fall_User_Weight_2014Fall_User`
    FOREIGN KEY (`2014Fall_User_id`)
    REFERENCES `vieiracf1_db`.`2014Fall_User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vieiracf1_db` ;

-- -----------------------------------------------------
-- Table `vieiracf1_db`.`2014Fall_Exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vieiracf1_db`.`2014Fall_Exercise` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `exercise_type` VARCHAR(45) NOT NULL,
  `distance` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `2014Fall_ExerciseType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_2014Fall_Exercise_2014Fall_ExerciseType1_idx` (`2014Fall_ExerciseType_id` ASC),
  CONSTRAINT `fk_2014Fall_Exercise_2014Fall_ExerciseType1`
    FOREIGN KEY (`2014Fall_ExerciseType_id`)
    REFERENCES `mydb`.`2014Fall_ExerciseType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vieiracf1_db`.`2014Fall_Food_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vieiracf1_db`.`2014Fall_Food_Type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vieiracf1_db`.`2014Fall_Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vieiracf1_db`.`2014Fall_Food` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  `calories` INT(11) NOT NULL,
  `fat` INT(11) NOT NULL,
  `carbs` INT(11) NOT NULL,
  `protein` INT(11) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `foodtype_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `foodtype_id` (`foodtype_id` ASC),
  CONSTRAINT `2014Fall_Food_ibfk_1`
    FOREIGN KEY (`foodtype_id`)
    REFERENCES `vieiracf1_db`.`2014Fall_Food_Type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
